[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_CONVEX_URL = "https://placeholder.convex.cloud"

[[plugins]]
  package = "@netlify/plugin-nextjs"